#!/bin/bash

# ==============================================================================
# The Manager: Triple Agent Orchestrator
# ==============================================================================
# This script orchestrates the handoff between Claude Worker and Claude QA agents 
# based on the `architecture_plan.md` generated by Anti-gravity.

WORKER_CONFIG="$HOME/Projects/AI_Workflow_Templates/claude_glm47_worker.json"
QA_CONFIG="$HOME/Projects/AI_Workflow_Templates/claude_glm47_qa.json"
PLAN_FILE="architecture_plan.md"

echo "========================================"
echo "🚀 Initiating Triple Agent Sprint"
echo "========================================"

# Pre-flight Check
if [ ! -f "$PLAN_FILE" ]; then
    echo "❌ Error: $PLAN_FILE not found in the current directory."
    echo "Please use Anti-gravity (The Architect) to generate the plan first."
    exit 1
fi

echo "✅ Found $PLAN_FILE"
echo ""

# ------------------------------------------------------------------------------
# Phase 1: The Worker Agent (Execution)
# ------------------------------------------------------------------------------
echo "👷 Spawning WORKER AGENT to execute the architecture plan..."

# NOTE: Claude Code currently uses inline arguments or an implicit project-level
# configuration instead of an explicit `--config` flag. To enforce the Strict XML,
# we temporarily copy the specific profile JSON into the project's .claude configs 
# before launching the shell.

mkdir -p .claude
cp "$WORKER_CONFIG" .claude/settings.json

# Launching Claude Code to read the plan and execute it
# DOCKER SANDBOX MODE: The worker runs inside an isolated MicroVM to protect the host OS.
docker sandbox run claude -- "--dangerously-skip-permissions --print \"Read $PLAN_FILE and execute all steps under Execution Steps. STOP after tool usage and await feedback. Do not proceed to verification.\""

# ------------------------------------------------------------------------------
# Phase 2: The QA/Tester Agent (Verification)
# ------------------------------------------------------------------------------
echo ""
echo "🔍 Worker Agent finished. Spawning QA AGENT for verification..."

# Replace the Worker settings with the QA settings
cp "$QA_CONFIG" .claude/settings.json

# Launching Claude Code to run tests
claude --dangerously-skip-permissions --print "Read section 3 VERIFICATION of $PLAN_FILE. Run the required commands and immediately generate qa_report.md"

# ------------------------------------------------------------------------------
# Cleanup
# ------------------------------------------------------------------------------
echo ""
echo "🧹 Sprint Completed. Restoring standard Claude Code settings..."
rm .claude/settings.json

echo "========================================"
echo "📝 Please check 'qa_report.md' for results."
echo "========================================"
