#!/bin/bash

# ==============================================================================
# The Manager: Triple Agent Orchestrator v2.0
# ==============================================================================
# This script orchestrates the handoff between Claude Worker and Claude QA agents
# based on the `architecture_plan.md` generated by Anti-gravity (The Architect).
#
# FIXES APPLIED (from Architecture Audit):
#   [T1] Removed invalid `docker sandbox` command → Native Claude CLI
#   [T2] Replaced settings.json copy → --system-prompt-file flag
#   [T3] Added exit code checks between phases
#   [T5] Race condition eliminated (no more settings.json mutation)
#   [T6] Added retry loop (max 3 attempts) with feedback

# ==============================================================================
# Configuration
# ==============================================================================
WORKER_PROMPT="$HOME/Projects/AI_Workflow_Templates/claude_glm47_worker_prompt.md"
QA_PROMPT="$HOME/Projects/AI_Workflow_Templates/claude_glm47_qa_prompt.md"
PLAN_FILE="architecture_plan.md"
QA_REPORT="qa_report.md"
MAX_ATTEMPTS=3

# ==============================================================================
# Trap: Guaranteed cleanup on exit (normal or crash)
# ==============================================================================
cleanup() {
    echo ""
    echo "🧹 Sprint cleanup complete."
}
trap cleanup EXIT

# ==============================================================================
# Pre-flight Checks
# ==============================================================================
echo "========================================"
echo "🚀 Initiating Triple Agent Sprint v2.0"
echo "========================================"

if [ ! -f "$PLAN_FILE" ]; then
    echo "❌ Error: $PLAN_FILE not found in the current directory."
    echo "Please use Anti-gravity (The Architect) to generate the plan first."
    exit 1
fi

if ! command -v claude &> /dev/null; then
    echo "❌ Error: 'claude' CLI not found. Please install Claude Code first."
    exit 1
fi

if [ ! -f "$WORKER_PROMPT" ]; then
    echo "❌ Error: Worker prompt file not found at $WORKER_PROMPT"
    exit 1
fi

if [ ! -f "$QA_PROMPT" ]; then
    echo "❌ Error: QA prompt file not found at $QA_PROMPT"
    exit 1
fi

echo "✅ Found $PLAN_FILE"
echo "✅ Claude CLI available"
echo "✅ Worker & QA prompt files loaded"
echo ""

# ==============================================================================
# Sprint Loop (Retry up to MAX_ATTEMPTS)
# ==============================================================================
for attempt in $(seq 1 $MAX_ATTEMPTS); do
    echo "========================================"
    echo "🔄 Sprint Attempt $attempt of $MAX_ATTEMPTS"
    echo "========================================"

    # --------------------------------------------------------------------------
    # Phase 1: The Worker Agent (Execution)
    # --------------------------------------------------------------------------
    echo ""
    echo "👷 Phase 1: Spawning WORKER AGENT..."

    claude --dangerously-skip-permissions \
      --system-prompt-file "$WORKER_PROMPT" \
      --print "Read $PLAN_FILE and execute all steps under the Execution Steps section. Write production-quality code. Do not proceed to verification."

    WORKER_EXIT=$?
    if [ $WORKER_EXIT -ne 0 ]; then
        echo "❌ WORKER CRASHED (Exit Code: $WORKER_EXIT)."
        if [ $attempt -eq $MAX_ATTEMPTS ]; then
            echo "💀 Max attempts reached. Manual intervention required."
            exit 1
        fi
        echo "⚠️ Retrying from scratch..."
        continue
    fi

    echo "✅ Worker phase completed successfully."

    # --------------------------------------------------------------------------
    # Phase 2: The QA/Tester Agent (Verification)
    # --------------------------------------------------------------------------
    echo ""
    echo "🔍 Phase 2: Spawning QA AGENT for verification..."

    claude --dangerously-skip-permissions \
      --system-prompt-file "$QA_PROMPT" \
      --print "Read section 3 VERIFICATION of $PLAN_FILE. Run ALL required test commands. Generate $QA_REPORT with STATUS: PASS or STATUS: FAIL."

    QA_EXIT=$?
    if [ $QA_EXIT -ne 0 ]; then
        echo "❌ QA AGENT CRASHED (Exit Code: $QA_EXIT)."
        if [ $attempt -eq $MAX_ATTEMPTS ]; then
            echo "💀 Max attempts reached. Manual intervention required."
            exit 1
        fi
        echo "⚠️ Retrying from scratch..."
        continue
    fi

    # --------------------------------------------------------------------------
    # Phase 3: Check QA Report
    # --------------------------------------------------------------------------
    if [ -f "$QA_REPORT" ] && grep -q "STATUS: PASS" "$QA_REPORT"; then
        echo ""
        echo "========================================"
        echo "✅ ALL TESTS PASSED on attempt $attempt!"
        echo "📝 See '$QA_REPORT' for full details."
        echo "========================================"
        exit 0
    fi

    echo "⚠️ QA Report indicates failure."
    if [ $attempt -eq $MAX_ATTEMPTS ]; then
        echo ""
        echo "========================================"
        echo "💀 SPRINT FAILED after $MAX_ATTEMPTS attempts."
        echo "📝 See '$QA_REPORT' for failure details."
        echo "========================================"
        exit 1
    fi
    echo "🔄 Retrying full sprint cycle..."
    echo ""
done
